/**
 * Docsector Page Feedback — Cloudflare Pages Function
 *
 * Auto-generated by docsector build. Do not edit manually.
 *
 * Records "Was this helpful?" votes as Workers Analytics Engine data points.
 * A request carries the reader's new `rating` and the `previous` one it
 * replaces (either may be null): the previous vote is cancelled by a
 * compensating point, so sums over the dataset stay exact.
 *
 *   indexes: [path (first 96 bytes)]
 *   blobs:   [path, locale, version, rating, action]  — action: vote | undo
 *   doubles: [score, count]  — vote: [1|0|-1, 1], undo: [-(1|0|-1), -1]
 */

/* global __FEEDBACK_CONFIG__ */

const FEEDBACK_CONFIG = __FEEDBACK_CONFIG__

const NO_STORE_HEADERS = {
  'Cache-Control': 'no-store'
}

const JSON_HEADERS = {
  'Content-Type': 'application/json; charset=utf-8',
  ...NO_STORE_HEADERS
}

const BODY_MAX_BYTES = 1024
const INDEX_MAX_BYTES = 96

const RATING_SCORES = Object.freeze({
  positive: 1,
  neutral: 0,
  negative: -1
})

// ? RFC 3986 path characters (printable ASCII minus `?`, `#`, quotes, `<>`,
//   `\`, `^`, `` ` `` and `{|}`) — a route path, never a URL or markup
const PATH_PATTERN = /^\/[!$%&()*+,\-./0-9:;=@A-Z[\]_a-z~]{0,255}$/

function errorResponse (code, message, status) {
  return new Response(JSON.stringify({ error: { code, message } }), {
    status,
    headers: JSON_HEADERS
  })
}

// : true when a browser says the vote comes from another site — requests
//   without an Origin (non-browser clients) pass
function isCrossOrigin (request) {
  const origin = request.headers.get('origin')
  if (origin === null) return false

  // ? The browser's own verdict wins when it sends one — it also holds behind
  //   a reverse proxy that serves the site under another host
  const site = request.headers.get('sec-fetch-site')
  if (site !== null) return site !== 'same-origin'

  try {
    return new URL(origin).host !== new URL(request.url).host
  } catch {
    // ? `Origin: null` (sandboxed frames, file://) is never this site
    return true
  }
}

// : request body as text, or null once it exceeds `limit` bytes — declared or
//   streamed, so a chunked upload cannot bypass the cap
async function readBoundedText (request, limit) {
  const declared = Number(request.headers.get('content-length'))
  if (Number.isFinite(declared) && declared > limit) return null
  if (!request.body) return ''

  const reader = request.body.getReader()
  const chunks = []
  let size = 0

  // @@ Drain the stream, stopping at the cap
  let chunk = await reader.read()
  while (!chunk.done) {
    size += chunk.value.byteLength
    if (size > limit) {
      await reader.cancel()
      return null
    }
    chunks.push(chunk.value)
    chunk = await reader.read()
  }

  const bytes = new Uint8Array(size)
  let offset = 0
  for (const part of chunks) {
    bytes.set(part, offset)
    offset += part.byteLength
  }

  return new TextDecoder().decode(bytes)
}

const isRating = (value) => typeof value === 'string' && Object.hasOwn(RATING_SCORES, value)

// : { vote } when every field is valid, { field } naming the first bad one
function validateVote (body) {
  if (!body || typeof body !== 'object' || Array.isArray(body)) return { field: 'body' }

  const { path, locale, version } = body
  const rating = body.rating ?? null
  const previous = body.previous ?? null

  if (rating !== null && !isRating(rating)) return { field: 'rating' }
  if (previous !== null && !isRating(previous)) return { field: 'previous' }
  // ? both empty, or the same vote twice — nothing to record
  if (rating === previous) return { field: 'rating' }
  if (typeof path !== 'string' || !PATH_PATTERN.test(path)) return { field: 'path' }
  if (typeof locale !== 'string' || !FEEDBACK_CONFIG.languages.includes(locale)) return { field: 'locale' }
  if (typeof version !== 'string' || !FEEDBACK_CONFIG.versions.includes(version)) return { field: 'version' }

  return { vote: { path, locale, version, rating, previous } }
}

// : one data point — `sign` 1 records `rating`, -1 cancels it
function buildDataPoint (vote, rating, sign) {
  return {
    // ? path is ASCII-only (PATH_PATTERN), so characters are bytes
    indexes: [vote.path.slice(0, INDEX_MAX_BYTES)],
    blobs: [vote.path, vote.locale, vote.version, rating, sign > 0 ? 'vote' : 'undo'],
    // ? `|| 0` keeps a cancelled neutral vote at 0, not -0
    doubles: [sign * RATING_SCORES[rating] || 0, sign]
  }
}

export async function onRequestPost (context) {
  const { request, env } = context

  // ? Browser votes from other sites never count
  if (isCrossOrigin(request)) {
    return errorResponse('forbidden_origin', 'Cross-origin feedback is not accepted.', 403)
  }

  // ? MIME essence, not a substring — `text/plain; x=application/json` is no JSON
  const contentType = (request.headers.get('content-type') || '').split(';')[0].trim().toLowerCase()
  if (contentType !== 'application/json') {
    return errorResponse('unsupported_media_type', 'Content-Type must be application/json.', 415)
  }

  const text = await readBoundedText(request, BODY_MAX_BYTES)
  if (text === null) {
    return errorResponse('payload_too_large', `Feedback body must not exceed ${BODY_MAX_BYTES} bytes.`, 413)
  }

  let body
  try {
    body = JSON.parse(text)
  } catch {
    return errorResponse('bad_request', 'Invalid JSON body.', 400)
  }

  const { vote, field } = validateVote(body)
  if (!vote) {
    // ? names the field only — a rejected vote must be visible to the operator
    //   without echoing reader-supplied values into the logs
    console.warn(`[docsector] Feedback vote rejected: invalid ${field}`)
    return errorResponse('invalid_vote', `Invalid feedback field: ${field}.`, 400)
  }

  const dataset = env?.[FEEDBACK_CONFIG.binding]
  if (!dataset || typeof dataset.writeDataPoint !== 'function') {
    console.error(`[docsector] Feedback binding ${FEEDBACK_CONFIG.binding} is not configured`)
    return errorResponse('feedback_not_configured', 'Feedback storage is not configured for this site.', 503)
  }

  // @ Cancel the previous vote, then record the new one
  try {
    if (vote.previous !== null) {
      dataset.writeDataPoint(buildDataPoint(vote, vote.previous, -1))
    }
    if (vote.rating !== null) {
      dataset.writeDataPoint(buildDataPoint(vote, vote.rating, 1))
    }
  } catch (error) {
    console.error(`[docsector] Feedback write failed: ${error?.message || String(error)}`)
    return errorResponse('feedback_write_failed', 'Feedback could not be recorded.', 500)
  }

  // : Accepted — nothing to send back
  return new Response(null, { status: 204, headers: NO_STORE_HEADERS })
}
