/**
 * Docsector AI Assistant — Cloudflare Pages Function
 *
 * Auto-generated by docsector build. Do not edit manually.
 */

/* global __AI_ASSISTANT_CONFIG__ */

const ASSISTANT_CONFIG = __AI_ASSISTANT_CONFIG__

const JSON_HEADERS = {
  'Content-Type': 'application/json; charset=utf-8',
  'Cache-Control': 'no-store'
}

const SSE_HEADERS = {
  'Content-Type': 'text/event-stream; charset=utf-8',
  'Cache-Control': 'no-cache, no-store',
  Connection: 'keep-alive'
}

function jsonResponse (body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: JSON_HEADERS
  })
}

function errorResponse (code, message, status = 500) {
  return jsonResponse({ error: { code, message } }, status)
}

function normalizeMessages (messages) {
  const validRoles = new Set(['system', 'developer', 'user', 'assistant', 'tool'])

  return (Array.isArray(messages) ? messages : [])
    .map((message) => {
      const role = validRoles.has(message?.role) ? message.role : 'user'
      const content = String(message?.content || '').trim()
      return content ? { role, content: content.slice(0, 4000) } : null
    })
    .filter(Boolean)
    .slice(-12)
}

function buildSystemPrompt (body) {
  const title = String(body?.context?.title || '').trim()
  const path = String(body?.route?.path || '').trim()
  const locale = String(body?.locale || '').trim()
  const selectedText = String(body?.context?.selectedText || '').trim()

  const lines = [
    'You are Docsector Assistant, a concise documentation assistant.',
    'Answer using the indexed documentation context. If the answer is not in the docs, say so clearly.',
    'Prefer short, actionable answers and cite the relevant source chunks when available.'
  ]

  if (locale) lines.push(`User locale: ${locale}.`)
  if (title || path) lines.push(`Current page: ${title || path}${path ? ` (${path})` : ''}.`)
  if (selectedText) lines.push(`Selected text from the page:\n${selectedText.slice(0, 1200)}`)

  return lines.join('\n')
}

function buildAiSearchOptions () {
  const aiSearch = ASSISTANT_CONFIG.aiSearch || {}
  const retrieval = {
    retrieval_type: aiSearch.retrievalType || 'hybrid',
    max_num_results: aiSearch.maxResults || 6,
    match_threshold: aiSearch.matchThreshold ?? 0.4,
    context_expansion: aiSearch.contextExpansion ?? 1
  }

  const options = {
    retrieval,
    query_rewrite: aiSearch.queryRewrite || { enabled: true },
    reranking: aiSearch.reranking || { enabled: false }
  }

  if (aiSearch.namespace && aiSearch.instanceName) {
    options.instance_ids = [aiSearch.instanceName]
  }

  return options
}

function buildCompletionPayload (body) {
  const messages = normalizeMessages(body?.messages)
  if (messages.length === 0) {
    throw new Error('Missing assistant messages')
  }

  return {
    messages: [
      { role: 'system', content: buildSystemPrompt(body) },
      ...messages
    ],
    model: ASSISTANT_CONFIG.aiSearch?.model,
    stream: ASSISTANT_CONFIG.aiSearch?.stream !== false,
    ai_search_options: buildAiSearchOptions()
  }
}

async function readJson (request) {
  const contentType = request.headers.get('content-type') || ''
  if (!contentType.toLowerCase().includes('application/json')) {
    throw new Error('Content-Type must be application/json')
  }

  return request.json()
}

async function callAiSearchBinding (env, payload) {
  const bindingName = ASSISTANT_CONFIG.aiSearch?.binding || 'AI_SEARCH'
  const binding = env?.[bindingName]
  if (!binding) return null

  const instanceName = ASSISTANT_CONFIG.aiSearch?.instanceName
  const target = typeof binding.get === 'function' && instanceName
    ? binding.get(instanceName)
    : binding

  if (!target || typeof target.chatCompletions !== 'function') {
    throw new Error(`AI Search binding ${bindingName} does not expose chatCompletions()`)
  }

  return target.chatCompletions(payload)
}

function buildAiSearchRestUrl (env) {
  const aiSearch = ASSISTANT_CONFIG.aiSearch || {}
  const accountId = env?.[aiSearch.accountIdEnv || 'CLOUDFLARE_ACCOUNT_ID']
  const instanceName = aiSearch.instanceName

  if (!accountId || !instanceName) {
    return null
  }

  const encodedAccount = encodeURIComponent(accountId)
  const encodedInstance = encodeURIComponent(instanceName)
  if (aiSearch.namespace) {
    return `https://api.cloudflare.com/client/v4/accounts/${encodedAccount}/ai-search/namespaces/${encodeURIComponent(aiSearch.namespace)}/instances/${encodedInstance}/chat/completions`
  }

  return `https://api.cloudflare.com/client/v4/accounts/${encodedAccount}/ai-search/instances/${encodedInstance}/chat/completions`
}

async function callAiSearchRest (env, payload) {
  const aiSearch = ASSISTANT_CONFIG.aiSearch || {}
  const apiToken = env?.[aiSearch.apiTokenEnv || 'CLOUDFLARE_API_TOKEN']
  const url = buildAiSearchRestUrl(env)

  if (!apiToken || !url) {
    throw new Error('AI Search REST credentials are not configured')
  }

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiToken}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(payload)
  })

  if (!response.ok) {
    const text = await response.text()
    throw new Error(`AI Search request failed with ${response.status}: ${text.slice(0, 240)}`)
  }

  return payload.stream
    ? response.body
    : response.json()
}

async function runAssistant (env, body) {
  const payload = buildCompletionPayload(body)
  const bindingResult = await callAiSearchBinding(env, payload)
  if (bindingResult) {
    return { payload, result: bindingResult }
  }

  return {
    payload,
    result: await callAiSearchRest(env, payload)
  }
}

async function createAssistantResponse (payload, result) {
  if (payload.stream) {
    if (result instanceof Response) {
      return new Response(result.body, {
        status: result.status,
        headers: SSE_HEADERS
      })
    }

    if (result?.body instanceof ReadableStream) {
      return new Response(result.body, { headers: SSE_HEADERS })
    }

    return new Response(result, { headers: SSE_HEADERS })
  }

  if (result instanceof Response) {
    return jsonResponse(await result.json(), result.status)
  }

  return jsonResponse(result)
}

export async function onRequestOptions () {
  return new Response(null, {
    status: 204,
    headers: {
      Allow: 'POST, OPTIONS'
    }
  })
}

export async function onRequestPost (context) {
  if (!ASSISTANT_CONFIG.enabled) {
    return errorResponse('assistant_disabled', 'AI Assistant is not enabled for this site.', 404)
  }

  let body
  try {
    body = await readJson(context.request)
  } catch (error) {
    return errorResponse('bad_request', error?.message || 'Invalid request body.', 400)
  }

  try {
    const { payload, result } = await runAssistant(context.env, body)
    return createAssistantResponse(payload, result)
  } catch (error) {
    const message = error?.message || 'Assistant request failed.'
    const isConfigError = /credentials|binding|configured/i.test(message)
    return errorResponse(isConfigError ? 'assistant_not_configured' : 'assistant_provider_error', message, isConfigError ? 503 : 502)
  }
}
